# Login to a custom agent mgmt app
# @name login
POST https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv CLIENT_ID}}&client_secret={{$dotenv CLIENT_SECRET}}&scope=https://graph.microsoft.com/.default&grant_type=client_credentials

###
# @name listBlueprints
GET https://graph.microsoft.com/beta/applications/microsoft.graph.agentIdentityBlueprint
Authorization: Bearer {{login.response.body.access_token}}


###====================== CREDENTIALS ===========================================================
# Create credentials for this app. Needs Application.ReadWrite.OwnedBy
# Recommended: use MI as federated credetial: https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/agent-id/identity-platform/create-blueprint.md#microsoft-graph-api-2
# use {{createBlueprintCredential.response.body.secretText}} to reference the created secret
# To reference the created secret use {{createBlueprintCredential.response.body.secretText}}. To reference the secret's id (keyId) use {{createBlueprintCredential.response.body.keyId}}. The keyId is needed for secret rotation (removing old secrets).
# @name createBlueprintCredential
POST https://graph.microsoft.com/beta/applications/{{listBlueprints.response.body.value[1].id}}/addPassword
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "displayName": "my-secret",
    "endDateTime": "2299-12-31T23:59:59Z"
}

###

# @name listBlueprintSecretKeys
GET https://graph.microsoft.com/v1.0/applications/{{listBlueprints.response.body.value[1].id}}?$select=id,displayName,passwordCredentials,federatedIdentityCredentials
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

###
# @name removePassword
POST https://graph.microsoft.com/v1.0/applications/{{listBlueprints.response.body.value[1].id}}/removePassword
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "keyId": "{{listBlueprintSecretKeys.response.body.passwordCredentials[0].keyId}}"
}


###
# subject is the objectId of the managed identity
# This link shows expected aud as 'api://AzureADTokenExchange/.default' but in practice it seems to be the appId of the blueprint app: 'fb60f99c-7a34-4190-8149-302f77469936'
# Its possible that the only way to get the au to be the uri, is to request it from an Azure resource (e.g. VM) using the MI, rather than directly from the token endpoint using client credentials flow with a federated credential. This would be a bit unfortunate as it would require additional setup of an Azure resource with the MI, but it would be in line with the idea that the federated credential is really meant for workloads running on Azure that want to authenticate with Azure AD without needing to manage secrets.
# https://learn.microsoft.com/en-us/entra/agent-id/identity-platform/create-blueprint?tabs=microsoft-graph-api#configure-credentials-for-the-agent-identity-blueprint
# Subject id=Managed Identity Object ID!!!
# @name createFederatedCredential
POST https://graph.microsoft.com/beta/applications/{{listBlueprints.response.body.value[1].id}}/federatedIdentityCredentials/
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "name": "FIC05",
    "issuer": "https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/v2.0",
    "subject": "/eid1/c/pub/t/DEllEbWJO0ayA4t34BWX0g/a/e5j6k1UJ9kC_BHj2IN_Zow/93fa987b-0955-40f6-bf04-78f620dfd9a3",
    "audiences": [
        "api://AzureADTokenExchange"
    ]
}

###
# @name listFederatedIdentityCredentials
GET https://graph.microsoft.com/v1.0/applications/{{listBlueprints.response.body.value[1].id}}/federatedIdentityCredentials
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

###
# @name deleteFederatedIdentityCredential
DELETE https://graph.microsoft.com/beta/applications/{{listBlueprints.response.body.value[1].id}}/federatedIdentityCredentials/{{listFederatedIdentityCredentials.response.body.value[0].id}} 
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}



###==========================================================================================
# https://learn.microsoft.com/en-us/entra/agent-id/identity-platform/autonomous-agent-request-tokens?tabs=Microsoft-graph-api
# https://learn.microsoft.com/en-us/entra/agent-id/identity-platform/agent-autonomous-app-oauth-flow#protocol-steps
###
# @name listAgentsForBlueprint
GET https://graph.microsoft.com/beta/servicePrincipals/microsoft.graph.agentIdentity?$filter=agentIdentityBlueprintId eq '{{listBlueprints.response.body.value[1].id}}'
Authorization: Bearer {{login.response.body.access_token}}

###
# @name deleteAgent
DELETE https://graph.microsoft.com/beta/servicePrincipals/{{listAgents.response.body.value[0].id}}
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

###
# @name requestBlueprintToken
POST https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{listBlueprints.response.body.value[1].appId}}
&scope=api://AzureADTokenExchange/.default
&grant_type=client_credentials
&client_secret={{createBlueprintCredential.response.body.secretText}}
&fmi_path={{listAgentsForBlueprint.response.body.value[0].agentAppId}}

###
# @name getServicePrincipalForAnAgent
GET https://graph.microsoft.com/v1.0/servicePrincipals?$filter=appId eq '{{listAgentsForBlueprint.response.body.value[0].agentAppId}}'
Authorization: Bearer {{login.response.body.access_token}}

###
# See https://learn.microsoft.com/en-us/entra/agent-id/identity-platform/autonomous-agent-request-agent-user-tokens?tabs=rest#create-an-agent-user
# Requires: user.ReadWrite.All; AgentIdUser.ReadWrite.IdentityParentedBy was not sufficient, probably needs adding to blueprint?
# @name createAgentUser
POST https://graph.microsoft.com/beta/users
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "@odata.type": "microsoft.graph.agentUser",
  "displayName": "New Agent User",
  "userPrincipalName": "agentuserupn@{{$dotenv TENANT_NAME}}",
  "identityParentId": "{{listAgents.response.body.value[3].id}}",
  "mailNickname": "agentuserupn",
  "accountEnabled": true
}

###
# @name getGraphSP
GET https://graph.microsoft.com/v1.0/servicePrincipals(appId = '00000003-0000-0000-c000-000000000000')
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

###
# Requires: DelegatedPermissionGrant.ReadWrite.All
# @name giveUserConsentedPermissions
POST https://graph.microsoft.com/v1.0/oauth2PermissionGrants
Authorization: Bearer {{login.response.body.access_token}}
Content-Type: application/json

{
  "clientId": "{{listAgents.response.body.value[3].id}}",
  "consentType": "Principal",
  "principalId": "{{createAgentUser.response.body.id}}",
  "resourceId": "{{getGraphSP.response.body.id}}",
  "scope": "Mail.Read"
}

#============================== Get agent user token ================================================================
# https://learn.microsoft.com/en-us/entra/agent-id/identity-platform/autonomous-agent-request-agent-user-tokens?tabs=rest#request-agent-user-token
###
# Get token as Blueprint app
# @name blueprintLogin
POST https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{listBlueprints.response.body.value[1].appId}}&client_secret={{createBlueprintCredential.response.body.secretText}}&scope=https://graph.microsoft.com/.default&grant_type=client_credentials

###
# @name getAgentIdentityToken


###
# @name getAgentUserToken
POST https://login.microsoftonline.com/<my-test-tenant>/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id=<agent-identity-id>
&scope=https://graph.microsoft.com/.default
&grant_type=user_fic
&client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer
&client_assertion=<agent-blueprint-token>
&user_id=<agent-user-object-id>
&user_federated_identity_credential=<agent-identity-token>