
# Based on https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-create-agent-identity-blueprint?tabs=cli2%2Cgraph-explorer&pivots=graph-explorer
# App must have AgentIdentityBlueprint.Create app permission. The app must be consented by a tenant admin. The app must be owned by the user creating the blueprint or the user must be a sponsor of the blueprint.
# https://learn.microsoft.com/en-us/powershell/module/microsoft.entra.applications/?view=entra-powershell has the PowerShell commands

###
@blueprintId    = {{listBlueprints.response.body.value[1].id}}
@blueprintAppId = {{listBlueprints.response.body.value[1].appId}}
@agentId        = {{listAgentsForBlueprint.response.body.value[0].id}}
@agentAppId     = {{listAgentsForBlueprint.response.body.value[0].appId}}

###
# @name login
POST https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv CLIENT_ID}}&client_secret={{$dotenv CLIENT_SECRET}}&scope=https://graph.microsoft.com/.default&grant_type=client_credentials

###

# https://learn.microsoft.com/en-us/graph/permissions-reference
# e1fe6dd8-ba31-4d61-89e7-88639da4683d - User.Read (delegated)
# 570282fd-fa5c-430d-a7fd-fc8dc98a9dca - Mail.Read (delegated)
# df021288-bdef-4463-88db-98f22de89214 - User.Read.All (application)
# 810c84a8-4a9e-49e6-bf7d-12d183f40d01 - Mail.Read (application)
# To create and consent to these permissions use setAgentPermissisons.ps1 script, 
# which requires AgentIdentityBlueprint.UpdateAuthProperties.All permission. Use Blueprint App Id when requested.
# Could also try: https://login.microsoftonline.com/{organization}/adminconsent?client_id={client-id}
# @name createBlueprint
POST https://graph.microsoft.com/v1.0/applications/microsoft.graph.agentIdentityBlueprint
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "displayName": "Blueprint V6",
    "description": "This is a blueprint for creating autonomous agents with Microsoft Graph API.",
    "appRoles": [
        {
            "id": "{{$guid}}",
            "displayName": "Reviewer",
            "description": "Allows viewing content produced by the agent.",
            "value": "invoker",
            "allowedMemberTypes": [
                "User", "Application"
            ]
        },
        {
            "id": "{{$guid}}",
            "displayName": "Agent configurer",
            "description": "Allows configuration of agent settings.",
            "value": "configurer",
            "allowedMemberTypes": [
                "User"
            ]
        }        
    ],
    "api": {
        "oauth2PermissionScopes": [
            {
                "id": "{{$guid}}",
                "type": "User",
                "value": "access_as_user",
                "isEnabled": true,
                "adminConsentDisplayName": "Access agent as user",
                "adminConsentDescription": "Allow the app to call the agent on behalf of the signed-in user.",
                "userConsentDisplayName": "Access agent as you",
                "userConsentDescription": "Allow this app to call the agent on your behalf."
            }
        ]
    },
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				},                
				{
					"id": "570282fd-fa5c-430d-a7fd-fc8dc98a9dca",
					"type": "Scope"
				},
                {
					"id": "df021288-bdef-4463-88db-98f22de89214",
					"type": "Role"
				},
                {
          "id": "810c84a8-4a9e-49e6-bf7d-12d183f40d01",
          "type": "Role"
        }
			]
		}
	],
    "sponsors@odata.bind": [
        "https://graph.microsoft.com/v1.0/users/{{$dotenv USER_OBJECT_ID}}"
    ],
    "owners@odata.bind": [
        "https://graph.microsoft.com/v1.0/users/{{$dotenv USER_OBJECT_ID}}"
    ]
}

###
# @name listBlueprints
GET https://graph.microsoft.com/v1.0/applications/microsoft.graph.agentIdentityBlueprint
Authorization: Bearer {{login.response.body.access_token}}

### ====================================== applicationUri is required for the blueprint to work, even though the documentation does not mention this requirement. The applicationUri can be any unique URI, it does not have to be a real URI. It is recommended to use a URI that is related to the appId for easier identification, for example: "api://{appId}".
# @name assignApplicationUri
PATCH https://graph.microsoft.com/v1.0/applications/{{blueprintId}}/microsoft.graph.agentIdentityBlueprint
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "identifierUris": [
        "api://{{blueprintId}}"
    ]
}

### Add all scopes and roles inheritance for MS Graph
# @name allowGraphPermissionsInheritance
POST https://graph.microsoft.com/v1.0/applications/microsoft.graph.agentIdentityBlueprint/{{blueprintAppId}}/inheritablePermissions
Content-Type: application/json
OData-Version: 4.0
Authorization: Bearer {{login.response.body.access_token}}

{
  "resourceAppId": "00000003-0000-0000-c000-000000000000",
  "inheritableScopes": {
    "@odata.type": "microsoft.graph.enumeratedScopes",
    "scopes": [
      "User.Read",
      "Mail.Read"
    ]
  },
  "inheritableRoles": {
    "@odata.type": "#microsoft.graph.allAllowedRoles",
    "kind": "allAllowed"
  }
}

### Get permissions
# @name getInheritablePermissions
GET https://graph.microsoft.com/v1.0/applications/{{blueprintId}}/microsoft.graph.agentIdentityBlueprint/inheritablePermissions
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

### Delete permissions
# @name deleteInheritablePermissions
DELETE https://graph.microsoft.com/v1.0/applications/{{blueprintId}}/microsoft.graph.agentIdentityBlueprint/inheritablePermissions/00000003-0000-0000-c000-000000000000
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### This app must have AgentIdentityPrincipal.Create app permission.
# @name createBlueprintServicePrincipal
POST https://graph.microsoft.com/v1.0/serviceprincipals/graph.agentIdentityBlueprintPrincipal
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "appId": "{{blueprintId}}"
}

###

# @name listServicePrincipal4Blueprint
GET https://graph.microsoft.com/v1.0/serviceprincipals/graph.agentIdentityBlueprintPrincipal?$filter=appId eq '{{blueprintId}}'
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

###
# Delegated permissions consented on the blueprint principal. Inheritable permissions only take effect if the blueprint principal has consent for them.
# @name getPermissionGrantsForBlueprintPrincipal
GET https://graph.microsoft.com/v1.0/servicePrincipals/{{listServicePrincipal4Blueprint.response.body.value[0].id}}/oauth2PermissionGrants
Authorization: Bearer {{login.response.body.access_token}}

###====================== CREDENTIALS ===========================================================
# Create credentials for this app so it can login to create agents from this client (Needs Application.ReadWrite.OwnedBy)
# Recommended: Run agent creation from an Azure-hosted process so it can use MI as federated credetial: https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/agent-id/identity-platform/create-blueprint.md#microsoft-graph-api-2
# use {{createBlueprintCredential.response.body.secretText}} to reference the created secret
# You will also need this value in the if you re-start the VSCode session and in the web
# app when using it without Managed Identity support (e.g. when running locally). 
# (I usually save it in the .env file as BLUEPRINT_PWD_CREDENTIAL so I can use in multiple runs
# and in the web app if I run it locally or without Managed Identity.)
# @name createBlueprintPasswordCredential
POST https://graph.microsoft.com/v1.0/applications/{{blueprintId}}/addPassword
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "displayName": "my-secret",
    "endDateTime": "2299-12-31T23:59:59Z"
}

###

# @name listBlueprintPasswordCredentials
GET https://graph.microsoft.com/beta/applications/{{blueprintId}}/passwordCredentials
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

###
# @name removePassword
POST https://graph.microsoft.com/v1.0/applications/{{blueprintId}}/removePassword
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "keyId": "{{listBlueprintPasswordCredentials.response.body.value[0].keyId}}"
}

###

# subject is the objectId of the managed identity
# This link shows expected aud as 'api://AzureADTokenExchange/.default' but in practice it seems to be the appId of the blueprint app: 'fb60f99c-7a34-4190-8149-302f77469936'
# Its possible that the only way to get the au to be the uri, is to request it from an Azure resource (e.g. VM) using the MI, rather than directly from the token endpoint using client credentials flow with a federated credential. This would be a bit unfortunate as it would require additional setup of an Azure resource with the MI, but it would be in line with the idea that the federated credential is really meant for workloads running on Azure that want to authenticate with Azure AD without needing to manage secrets.
# https://learn.microsoft.com/en-us/entra/agent-id/identity-platform/create-blueprint?tabs=microsoft-graph-api#configure-credentials-for-the-agent-identity-blueprint
# Subject id=Managed Identity Object ID!!!
# @name createFederatedCredential
POST https://graph.microsoft.com/v1.0/applications/{{blueprintId}}/federatedIdentityCredentials/
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "name": "Fed01",
    "issuer": "https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/v2.0",
    "subject": "{{$dotenv MANAGED_IDENTITY_OBJ_ID}}",
    "audiences": [
        "api://AzureADTokenExchange"
    ]
}

# IMPORTANT: save the created secretText from the response in the .env file to use in future runs as it exists during this run.

###
# @name listFederatedIdentityCredentials
GET https://graph.microsoft.com/v1.0/applications/{{blueprintId}}/federatedIdentityCredentials
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

###
# @name deleteFederatedIdentityCredential
DELETE https://graph.microsoft.com/beta/applications/{{blueprintId}}/federatedIdentityCredentials/{{listFederatedIdentityCredentials.response.body.value[0].id}} 
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### ===================================== Create an agent from the blueprint. The agent will be created with the same app roles and permissions as defined in the blueprint. The agent will also be assigned to the same sponsors as the blueprint. The agent will have a service principal created for it, which can be used to assign additional permissions to the agent if needed.
# Get token as Blueprint app
# @name blueprintLogin
POST https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{blueprintAppId}}&client_secret={{$dotenv BLEPRINTV2_PWD_CREDENTIAL}}&scope=https://graph.microsoft.com/.default&grant_type=client_credentials

###
# Create agent; must be blueprint app; CreateAsManager permission was not assigned!
# @name createAgent
POST https://graph.microsoft.com/v1.0/servicePrincipals/microsoft.graph.agentIdentity
Content-Type: application/json
Authorization: Bearer {{blueprintLogin.response.body.access_token}}

{
  "displayName": "Agent 001 for Blueprint V6",
  "agentIdentityBlueprintId": "{{blueprintAppId}}",
  "sponsors@odata.bind": [
    "https://graph.microsoft.com/v1.0/users/{{$dotenv USER_OBJECT_ID}}"
  ]
}

###
# @name listAllAgents
GET https://graph.microsoft.com/v1.0/servicePrincipals/microsoft.graph.agentIdentity
Authorization: Bearer {{login.response.body.access_token}}

###
# @name deleteAgent
DELETE https://graph.microsoft.com/v1.0/servicePrincipals/{{listAllAgents.response.body.value[0].id}}
Authorization: Bearer {{blueprintLogin.response.body.access_token}}

###
# @name listAgentsForBlueprint
GET https://graph.microsoft.com/v1.0/servicePrincipals/microsoft.graph.agentIdentity?$filter=agentIdentityBlueprintId eq '{{blueprintId}}'
Authorization: Bearer {{login.response.body.access_token}}

### -------------------------------------------------------------------------------
### Cleanup

# @name listBlueprintServicePrincipals
GET https://graph.microsoft.com/v1.0/servicePrincipals/microsoft.graph.agentIdentityBlueprintPrincipal
Authorization: Bearer {{login.response.body.access_token}}

### 
# @name deleteServicePrincipalForBlueprint
DELETE https://graph.microsoft.com/v1.0/servicePrincipals/{{listBlueprintServicePrincipals.response.body.value[0].id}}
Authorization: Bearer {{login.response.body.access_token}}

###
# @name deleteBlueprint
DELETE https://graph.microsoft.com/beta/applications/{{blueprintId}}/microsoft.graph.agentIdentityBlueprint
Authorization: Bearer {{login.response.body.access_token}}


