
# Based on https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-create-agent-identity-blueprint?tabs=cli2%2Cgraph-explorer&pivots=graph-explorer
# App must have AgentIdentityBlueprint.Create app permission. The app must be consented by a tenant admin. The app must be owned by the user creating the blueprint or the user must be a sponsor of the blueprint.

# @name login
POST https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv CLIENT_ID}}&client_secret={{$dotenv CLIENT_SECRET}}&scope=https://graph.microsoft.com/.default&grant_type=client_credentials

###

# @name createBlueprint
POST https://graph.microsoft.com/beta/applications/
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "@odata.type": "Microsoft.Graph.AgentIdentityBlueprint",
    "displayName": "Blueprint V4",
    "description": "This is a blueprint for creating autonomous agents with Microsoft Graph API.",
    "sponsors@odata.bind": [
        "https://graph.microsoft.com/v1.0/users/{{$dotenv USER_OBJECT_ID}}",
    ],
    "owners@odata.bind": [
        "https://graph.microsoft.com/v1.0/users/{{$dotenv USER_OBJECT_ID}}"
    ],
    "appRoles": [
        {
            "id": "{{$guid}}",
            "displayName": "Invoker",
            "description": "Allows invocation of agent actions.",
            "value": "invoker",
            "allowedMemberTypes": [
                "User", "Application"
            ]
        },
        {
            "id": "{{$guid}}",
            "displayName": "Agent configurer",
            "description": "Allows configuration of agent settings.",
            "value": "configurer",
            "allowedMemberTypes": [
                "User"
            ]
        }        
    ],
    "api": {
        "oauth2PermissionScopes": [
            {
                "id": "{{$guid}}",
                "type": "User",
                "value": "access_as_user",
                "isEnabled": true,
                "adminConsentDisplayName": "Access agent as user",
                "adminConsentDescription": "Allow the app to call the agent on behalf of the signed-in user.",
                "userConsentDisplayName": "Access agent as you",
                "userConsentDescription": "Allow this app to call the agent on your behalf."
            }
        ]
    },
	"requiredResourceAccess": [
		{
			"resourceAppId": "00000003-0000-0000-c000-000000000000",
			"resourceAccess": [
				{
					"id": "e1fe6dd8-ba31-4d61-89e7-88639da4683d",
					"type": "Scope"
				},                
				{
					"id": "570282fd-fa5c-430d-a7fd-fc8dc98a9dca",
					"type": "Scope"
				}
			]
		}
	]   
}

###

# @name listBlueprints
GET https://graph.microsoft.com/beta/applications/microsoft.graph.agentIdentityBlueprint
Authorization: Bearer {{login.response.body.access_token}}

### ====================================== applicationUri is required for the blueprint to work, even though the documentation does not mention this requirement. The applicationUri can be any unique URI, it does not have to be a real URI. It is recommended to use a URI that is related to the appId for easier identification, for example: "api://{appId}".
# @name assignApplicationUri
PATCH https://graph.microsoft.com/beta/applications/{{listBlueprints.response.body.value[2].id}}/microsoft.graph.agentIdentityBlueprint
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "identifierUris": [
        "api://{{listBlueprints.response.body.value[2].id}}"
    ]
}

###

###
# NOTE: you still need to grant these OAuth2 permissions via the Portal consent: Enterpise App->Search by id->Permissions->Grant admin consent
# @name addInheritablePermissions
POST https://graph.microsoft.com/beta/applications/{{listBlueprints.response.body.value[2].id}}/microsoft.graph.agentIdentityBlueprint/inheritablePermissions
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "resourceAppId": "00000003-0000-0000-c000-000000000000",
  "inheritableScopes": {
    "@odata.type": "microsoft.graph.enumeratedScopes",
    "scopes": [
      "User.Read",
      "Mail.Read"
    ]
  }
}

### This app must have AgentIdentityPrincipal.Create app permission.
# @name createBlueprintServicePrincipal
POST https://graph.microsoft.com/beta/serviceprincipals/graph.agentIdentityBlueprintPrincipal
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "appId": "{{listBlueprints.response.body.value[2].id}}"
}

###

# @name listServicePrincipal4Blueprint
GET https://graph.microsoft.com/beta/serviceprincipals/graph.agentIdentityBlueprintPrincipal?$filter=appId eq '{{listBlueprints.response.body.value[2].id}}'
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


###====================== CREDENTIALS ===========================================================
# Create credentials for this app. Needs Application.ReadWrite.OwnedBy
# Recommended: use MI as federated credetial: https://github.com/MicrosoftDocs/entra-docs/blob/main/docs/agent-id/identity-platform/create-blueprint.md#microsoft-graph-api-2
# use {{createBlueprintCredential.response.body.secretText}} to reference the created secret
# @name createBlueprintPasswordCredential
POST https://graph.microsoft.com/beta/applications/{{listBlueprints.response.body.value[2].id}}/addPassword
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "displayName": "my-secret",
    "endDateTime": "2299-12-31T23:59:59Z"
}

###

# @name listBlueprintPasswordCredentials
GET https://graph.microsoft.com/beta/applications/{{listBlueprints.response.body.value[2].id}}/passwordCredentials
OData-Version: 4.0
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

###

###

# @name removePassword
POST https://graph.microsoft.com/v1.0/applications/{{listBlueprints.response.body.value[2].id}}/removePassword
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "keyId": "{{listBlueprintPasswordCredentials.response.body.value[0].keyId}}"
}

###

# subject is the objectId of the managed identity
# This link shows expected aud as 'api://AzureADTokenExchange/.default' but in practice it seems to be the appId of the blueprint app: 'fb60f99c-7a34-4190-8149-302f77469936'
# Its possible that the only way to get the au to be the uri, is to request it from an Azure resource (e.g. VM) using the MI, rather than directly from the token endpoint using client credentials flow with a federated credential. This would be a bit unfortunate as it would require additional setup of an Azure resource with the MI, but it would be in line with the idea that the federated credential is really meant for workloads running on Azure that want to authenticate with Azure AD without needing to manage secrets.
# https://learn.microsoft.com/en-us/entra/agent-id/identity-platform/create-blueprint?tabs=microsoft-graph-api#configure-credentials-for-the-agent-identity-blueprint
# Subject id=Managed Identity Object ID!!!
# @name createFederatedCredential
POST https://graph.microsoft.com/beta/applications/{{listBlueprints.response.body.value[2].id}}/federatedIdentityCredentials/
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
    "name": "Fed01",
    "issuer": "https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/v2.0",
    "subject": "{{$dotenv MANAGED_IDENTITY_OBJ_ID}}",
    "audiences": [
        "api://AzureADTokenExchange"
    ]
}

###
# @name listFederatedIdentityCredentials
GET https://graph.microsoft.com/v1.0/applications/{{listBlueprints.response.body.value[2].id}}/federatedIdentityCredentials
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

###
# @name deleteFederatedIdentityCredential
DELETE https://graph.microsoft.com/beta/applications/{{listBlueprints.response.body.value[2].id}}/federatedIdentityCredentials/{{listFederatedIdentityCredentials.response.body.value[0].id}} 
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}


### ===================================== Create an agent from the blueprint. The agent will be created with the same app roles and permissions as defined in the blueprint. The agent will also be assigned to the same sponsors as the blueprint. The agent will have a service principal created for it, which can be used to assign additional permissions to the agent if needed.
# Get token as Blueprint app
# @name blueprintLogin
POST https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{listBlueprints.response.body.value[2].appId}}&client_secret={{createBlueprintPasswordCredential.response.body.secretText}}&scope=https://graph.microsoft.com/.default&grant_type=client_credentials

###
# Create agent; must be blueprint app; CreateAsManager permission was not assigned!
# @name createAgent
POST https://graph.microsoft.com/beta//servicePrincipals/microsoft.graph.agentIdentity
Content-Type: application/json
Authorization: Bearer {{blueprintLogin.response.body.access_token}}

{
  "displayName": "Agent V4a",
  "agentIdentityBlueprintId": "{{listBlueprints.response.body.value[2].appId}}",
  "sponsors@odata.bind": [
    "https://graph.microsoft.com/v1.0/users/{{$dotenv USER_OBJECT_ID}}"
  ]
}

###
# @name listAllAgents
GET https://graph.microsoft.com/beta/servicePrincipals/microsoft.graph.agentIdentity
Authorization: Bearer {{login.response.body.access_token}}

###
# @name deleteAgent
DELETE https://graph.microsoft.com/beta/servicePrincipals/{{listAllAgents.response.body.value[2].id}}
Authorization: Bearer {{blueprintLogin.response.body.access_token}}

###
# @name listAgentsForBlueprint
GET https://graph.microsoft.com/beta/servicePrincipals/microsoft.graph.agentIdentity?$filter=agentIdentityBlueprintId eq '{{listBlueprints.response.body.value[2].id}}'
Authorization: Bearer {{login.response.body.access_token}}

###
# @name setPermissionGrantsForAgent
POST https://graph.microsoft.com/v1.0/oauth2PermissionGrants
Content-Type: application/json

{
  "clientId": "{{listAgentsForBlueprint.response.body.value[1].id}}",
  "consentType": "AllPrincipals",
  "resourceId": "00000003-0000-0000-c000-000000000000",
  "scope": "Mail.Read"
}

###
# @name getPermissionGrantsForAnAgent
GET https://graph.microsoft.com/v1.0/servicePrincipals/{{listAgentsForBlueprint.response.body.value[1].id}}/oauth2PermissionGrants
Authorization: Bearer {{login.response.body.access_token}}

###
# @name assignRole
POST https://graph.microsoft.com/beta/servicePrincipals/{{createBlueprintServicePrincipal.response.body.id}}/appRoleAssignments
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

{
  "principalId": "{{$dotenv USER_OBJECT_ID}}",
  "resourceId": "{{createBlueprintServicePrincipal.response.body.id}}",
  "appRoleId": "{{listBlueprints.response.body.value[2].appRoles[0].id}}"
}

### Get autonomous agent token using the blueprint app credentials. This token can be used to call Microsoft Graph API on behalf of the agent. The token will have the permissions defined in the blueprint.
# Error: AADSTS70003: The app requested an unsupported grant type 'client_credentials,client_credentials
# @name blueprintLogin4Federation
POST https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{listBlueprints.response.body.value[2].appId}}&
client_secret={{createBlueprintPasswordCredential.response.body.secretText}}&
scope=api://AzureADTokenExchange/.default&
grant_type=client_credentials&
fmi_path={{listAgentsForBlueprint.response.body.value[0].agentAppId}}

# Errors: AADSTS700211: No matching federated identity record found for presented assertion issuer
# @name acquireAutonomousToken
POST https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{listAgentsForBlueprint.response.body.value[0].agentAppId}}&
scope=https://graph.microsoft.com/.default&
client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&
client_assertion={{blueprintLogin.response.body.access_token}}&
grant_type=client_credentials

# Use portal to assign "Agent configurer" role to the user, which allows the user to configure agent settings in the portal. This role cannot be assigned via Graph API as it is a user role and not an application role.

### =================================================================================
# @name getTokenForUser
POST https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/oauth2/v2.0/devicecode
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv PUBLIC_CLIENT_ID}}&scope=api://{{createBlueprint.response.body.id}}/.default

###
# @name getUserTokenResponse
POST https://login.microsoftonline.com/{{$dotenv TENANT_ID}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv PUBLIC_CLIENT_ID}}&grant_type=urn:ietf:params:oauth:grant-type:device_code&device_code={{getTokenForUser.response.body.device_code}}


### -------------------------------------------------------------------------------
### Cleanup

# @name listBlueprintServicePrincipals
GET https://graph.microsoft.com/v1.0/servicePrincipals/microsoft.graph.agentIdentityBlueprintPrincipal
Authorization: Bearer {{login.response.body.access_token}}

### 
# @name deleteServicePrincipalForBlueprint
DELETE https://graph.microsoft.com/v1.0/servicePrincipals/{{listBlueprintServicePrincipals.response.body.value[2].id}}
Authorization: Bearer {{login.response.body.access_token}}

###
# @name deleteBlueprint
DELETE https://graph.microsoft.com/beta/applications/{{listBlueprints.response.body.value[2].id}}/microsoft.graph.agentIdentityBlueprint
Authorization: Bearer {{login.response.body.access_token}}


### -------------------------------------------------------------------------------
### Reporting

###
# @name listAgentInstances
GET https://graph.microsoft.com/beta//agentRegistry/agentInstances
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}

###
# @name listManifests
GET https://graph.microsoft.com/beta/GET /agentRegistry/agentInstances/{agentInstanceId}/agentCardManifest
Content-Type: application/json
Authorization: Bearer {{login.response.body.access_token}}